### ISSUE TITLE
Warning for unsupported browsers

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#122]
It's fairly easy to detect if certain browsers don't support essential features of the tool.Users should be shown a warning that their browser isn't supported.

**Comment by WilcoFiers** [comment]
The test looks if FileReader and Blob are supported, which are required for loading and saving the JSON data respectively. What text would you suggest for the error message?

**Comment by nitedog** [comment]
Changed to "The web browser you are using does not support some functionality, such as saving and loading reports. You can continue to use this report tool with limited functionality, or you may be able to update or use a different web browser." (pending EOWG approval)

**Comment by slhenry** [comment]
I still think we need to link to information on which browsers are supported.

Also, I suggest something more like this for the wording:
This web browser version does not support some of the functionality of this tool, including saving and loading reports. You can continue to use this tool with limited functionality. We suggest that you use an updated or different web browser that supports all of the functionality of this tool. _List of browsers supported_.

Not a show-stopper; I'm OK leaving this for the next update.

**Comment by nitedog** [comment]
We can easily produce such a list, and certainly not maintain it. The tool just checks if particular APIs are supported or not, rather than to check the browser version against a list. The message now says:

"The web browser you are using does not support some functionality, such as saving and loading reports. You can continue to use this report tool with limited functionality. Update or use a different web browser to make use of all functionality of this report tool."
