### ISSUE TITLE
Have import be async

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-em-report-tool#257]
The JSON-LD library is build to do tasks async, the import module however, doesn't communicate when the model is ready. This is poorly written and quite brittle because of it.

**Comment by nitedog** [comment]
@rvantonisse what is the latest on how you addressed this? cc. @hidde @mhansma96

**Comment by rvantonisse-accessibility** [comment]
There needs to be a little clarification here since at the time of writing this issue the current import functionality did not exist. Import here is a reference to the `Open evaluation` functionality.

Concerning asynchronous Opening an evaluation: 

I think this is an issue of UI update / status messaging part and
a more performant data loading part specificly within the ecosystem of AngularJS 1.X.

With the new tool written with Svelte I did not encounter any problems in performance or Svelte not being able to handle the data update when opening an evaluation.

Consider this issue open here, but closed or low priority in the new tool `wai-wcag-em-report-tool`.

**Comment by nitedog** [comment]
Great, thanks for this clarification @rvantonisse-accessibility. I added the corresponding label as this is considered fixed in the new version.

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which I believe the described performance issue no longer applies. Closing this issue as we' don't plan on work on the `2.*.*` versions anymore.
