### ISSUE TITLE
Abbreviations: expansions and ECMA to JS

### ISSUE THREAD

**Issue by susanatx** [w3c/wcag-em-report-tool#279]
Expand or define acronyms throughout and use Javascript instead of ECMA as it's a more widely used term. (comment from EO usability lab)

**Comment by WilcoFiers** [comment]
Good suggestion

**Comment by hidde** [comment]
To update on this (and thanks for your patience :-) )… in the 2021 rebuild ([preview of the 2021 rebuild](https://wcag-em-report-tool-2021-redesign.netlify.app/)) we use JavaScript instead of ECMA. 

Abbreviations are also expanded on their first use, except for very common ones like HTML, CSS, JSON, WAI-ARIA, I feel that for those, the abbreviations may be more widely known than the expanded version?

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which we use JavaScript and show expanded versions except for abbreviations where the abbreviation is more common than the expanded variant, such as HTML.
