### ISSUE TITLE
Poor typing performance 

### ISSUE THREAD

**Issue by roelvangils** [w3c/wcag-em-report-tool#288]
When inside the textarea `<textarea class="assert_description">`, I noticed typing is sluggish. In Safari (11.0.2), it's unworkable. In Chrome, it's far less noticable, but still not comfortable to type long texts.

I suspect the `keyup` and `keydown` event listeners on the textarea are causing this.

I made a small screencasts to demonstrate this behavior: https://cl.ly/1u0l0w2R0t1q

**Comment by rvantonisse** [comment]
Will check if fixed with framework update in pr #300

**Comment by rvantonisse** [comment]
Will fix with new implementation

**Comment by hidde** [comment]
Have added the “fixed in 2021 redesign“ label, as we are rebuilding the tool and we expect this bug to be fixed with the rebuild. Many thanks for your patience, @roelvangils.

Feel free to try out typing some long texts in the [preview of the 2021 redesign](wcag-em-report-tool-2021-redesign.netlify.app/) (expand the principles on the audit page to see the text areas). FWIW, I did in Safari, Firefox and Chrome and notice no sluggishness.

**Comment by hidde** [comment]
Hey Roel and Roel, 

We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which there should be great typing performance. Please get in touch if it still isn't as smooth as you would expect and we will look into it. 

Thanks!
