### ISSUE TITLE
Update wcag2-nl.json with Dutch translation of WCAG 2.1

### ISSUE THREAD

**Issue by ghost** [w3c/wcag-em-report-tool#358]
Issue was raised by mail and asked for a fix to the Dutch translation.

Will be able to do so thanks to work on official translation of [WCAG 2.1 in Dutch](https://github.com/AccessibilityNL/WCAG21-NL)

**Comment by julezrulez** [comment]
When will the Dutch translation be available?

**Comment by rvantonisse-accessibility** [comment]
Hej @julezrulez !

I'll give this a shot today. If all goes well I will post a link here to a preview version.

Currently I am also working hard on a complete rebuild, which can be tracked at #360 . A preview of this progress is available at https://accessibilitynl.github.io/wcag-em-report-tool/svelte-preview/

**Comment by rvantonisse-accessibility** [comment]
Hey @julezrulez ,

The dutch wcag translation is in. You can preview the app at https://w3c.github.io/wcag-em-report-tool/dist/#!/evaluation/audit

Let me know if this works!

**Comment by julezrulez** [comment]
Hi Roel,  I have worked with the tool a few days now, but haven't published a report yet. Might be 1 or 2 reports today. Could you test 1 thing? If I set the tool in Dutch and I load an json file which yet has lang="en" the tool automatically switches to English which is correct. But when I switch to Dutch with the loaded text I get no fields in Step 4. Haven't time to test it all over again.. If necessary I can e-mail you the file I tested it with. E-mail me on my business e-mail please for that, because I am not that often in the mailbox where I signed in for github.

**Comment by hidde** [comment]
Closing this issue, as we recently launched the 3.0.0 version of the WCAG-EM Report Tool, in which it no longer applies: WCAG 2.1 is fully supported in Dutch.
