### ISSUE TITLE
[Redesign] Warn before closing tab or leaving page

### ISSUE THREAD

**Issue by hidde** [w3c/wcag-em-report-tool#421]
Because the evaluation is not [saved locally, see #7](https://github.com/w3c/wcag-em-report-tool/issues/7), users will lose all their input when they close their tab. 

In the currently live version, a warning is shown before the tab is closed. Let's add that in the redesign, too.

**Comment by hidde** [comment]
This would not be needed if we fix #7

**Comment by mhansma96** [comment]
In the current live version this only happens if you have added/editted any input fields. Is this conditioned by checking if anything is added to the localstorage? Because at the moment in the new version, we cannot do that check so in that case, are the answers being held somewhere else that we can check to make a valid condition?
