### ISSUE TITLE
[high] View Report - summary counter not working well

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-em-report-tool#498]
In this [evaluation report](https://github.com/w3c/wcag-em-report-tool/files/6701290/evaluation.zip) only the passes are counted (not the cannot tell and the not present).

**Comment by mhansma96** [comment]
Seems like something goes wrong when adding some information on the define scope page, this issue happens. 

Try this scenario: 

- Go immediately to the audit sample page
- Change the value of a criteria
- Go to the view report page - the summary counters are working
- Go to the define scope page, add a title
- Go back to the audit sample page - your report bars are empty
- Go to the view report page - summary is all 0

@nitedog @hidde

**Comment by mhansma96** [comment]
In PR #500 I have added a solution for this. Now the counters should always be correct. Please feel free to test this with the report or with another example if possible.
An extra bonus from fixing this issue is that the criteria are now initialized from the define scope page, so they're available from that point and we have more control over how this initialization works now

**Comment by hidde** [comment]
This should be fixed now.
