### ISSUE TITLE
Allow the addition of screenshots from the interface

### ISSUE THREAD

**Issue by TalyahAtUXAccess** [w3c/wcag-em-report-tool#518]
Sometimes it is important to provide a screenshot of a specific area of the screen being audited that is associated with the reported issue.

**Comment by hidde** [comment]
Agreed! The [redesign](https://w3c.github.io/wai-wcag-em-report-tool/) (version 3.0.0) will allow you to embed images using Markdown. You will need to host them somewhere first, this is because we purposefully don't store any of your data, it all happens in your browser. We won't be able to address it in the current version (version 2.0.1).
