### ISSUE TITLE
Provide an Editor toolbar to allow semantics on the observation content 

### ISSUE THREAD

**Issue by TalyahAtUXAccess** [w3c/wcag-em-report-tool#519]
Perhaps you can provide an editor toolbar to allow auditors to structure their content using proper semantics like headings, lists, links, bold text etc.

**Comment by hidde** [comment]
This won't be available in the current tool, but the [new tool](https://github.com/w3c/wai-wcag-em-report-tool/) allows for Markdown input, so that you can do headings. lists, links, bold text and much more!

You can try this out on https://wcag-em-report-tool-2021-redesign.netlify.app/.  Let us know what you think, feedback for this new version can be filed in the [wai-wcag-em-report-tool](https://github.com/w3c/wai-wcag-em-report-tool/) repo (this repo is for the current tool only).

**Comment by hidde** [comment]
We recently launched the 3.0.0 version of the WCAG-EM Report Tool, where Markdown support is added as described above.
